Pointages/Models/Pointeuse.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;


namespace Pointages.Models
{
    [Table("Pointeuse", Schema = "public")]
    public class Pointeuse 
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        bool Isprinc { get; set; }

        
        public static string GetGeneralLogData(zkemkeeper.CZKEM axCZKEM1, string ip, int port)
        {
            String data = "";
            if (axCZKEM1.Connect_Net(ip, port) == false)
            {
                data = "Please connect the device first";

            }
            else
            {
                string sdwEnrollNumber = "";
                //int idwTMachineNumber=0;
                //int idwEMachineNumber=0;
                int idwVerifyMode = 0;
                int idwInOutMode = 0;
                int idwYear = 0;
                int idwMonth = 0;
                int idwDay = 0;
                int idwHour = 0;
                int idwMinute = 0;
                int idwSecond = 0;
                int idwWorkcode = 0;

                int idwErrorCode = 0;
                int iGLCount = 0;
                int iIndex = 0;
                
                axCZKEM1.EnableDevice(1, false);//disable the device
                if (axCZKEM1.ReadGeneralLogData(1))//read all the attendance records to the memory
                {
                    while (axCZKEM1.SSR_GetGeneralLogData(1, out sdwEnrollNumber, out idwVerifyMode,
                               out idwInOutMode, out idwYear, out idwMonth, out idwDay, out idwHour, out idwMinute, out idwSecond, ref idwWorkcode))//get records from the memory
                    {
                        iGLCount++;
                 
                        data = data + sdwEnrollNumber+" "+ idwVerifyMode.ToString()+" "+ idwInOutMode.ToString()+" "+ idwYear.ToString() + "-" + idwMonth.ToString() + "-" + idwDay.ToString() + " " + idwHour.ToString() + ":" + idwMinute.ToString() + ":" + idwSecond.ToString();
                        iIndex++;
                    }
                }
                else
                {
                   
                    axCZKEM1.GetLastError(ref idwErrorCode);

                    if (idwErrorCode != 0)
                    {
                        data="Reading data from terminal failed,ErrorCode: " + idwErrorCode.ToString();
                    }
                    else
                    {
                        data="No data from terminal returns!";
                    }
                }
                axCZKEM1.EnableDevice(1, true);//enable the device
            }
                return data;
        }

    }

}

Pointages/Controllers/HomeController.cs
using Pointages.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pointages.Controllers
{
    public class HomeController : Controller
    {
        private PointageContext db = new PointageContext();

        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Pointages/Controllers/PointeusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pointages.DAL;
using Pointages.Shared;
using Pointages.Models;
namespace Pointages.Controllers
{
    public class PointeusesController : Controller
    {
        private PointageContext db = new PointageContext();
        // GET: Pointeuses
        public ActionResult Index()
        {
            return View(db.Pointeuses.ToList());
        }

        // GET: Pointeuses/Edit/5
        public ActionResult Connect(int? id)
        {
            GlobalVariables.axCZKEM.Disconnect();
            Pointeuse pointeuse = db.Pointeuses.Find(id);
            //try connect
            if (GlobalVariables.axCZKEM.Connect_Net(pointeuse .IP,pointeuse .Port) == true)
                TempData["Success"] = "Pointeuse Connectée";

            else
                TempData["Success"] = "Pointeuse non Connectée";

            return RedirectToAction("Index");
        }

        public ActionResult DisConnect(int? id)
        {

            Pointeuse pointeuse = db.Pointeuses.Find(id);
            //try connect
            GlobalVariables.axCZKEM.Disconnect();

            TempData["Success"] = "Pointeuse Déconnectée";

            return RedirectToAction("Index");
        }
        public ActionResult Read(int? id)
        {

            Pointeuse pointeuse = db.Pointeuses.Find(id);
            
            String data=Pointeuse.GetGeneralLogData(GlobalVariables.axCZKEM, pointeuse.IP, pointeuse.Port);
            
            TempData["Success"] = data;

            return RedirectToAction("Index");
        }
        // GET: Pointeuses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pointeuse pointeuse = db.Pointeuses.Find(id);
            if (pointeuse == null)
            {
                return HttpNotFound();
            }
            return View(pointeuse);
        }

        // GET: Pointeuses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pointeuses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,IP,Port")] Pointeuse pointeuse)
        {
            if (ModelState.IsValid)
            {
                db.Pointeuses.Add(pointeuse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pointeuse);
        }

        // GET: Pointeuses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pointeuse pointeuse = db.Pointeuses.Find(id);
            if (pointeuse == null)
            {
                return HttpNotFound();
            }
            return View(pointeuse);
        }


        // POST: Pointeuses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,IP,Port")] Pointeuse pointeuse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pointeuse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pointeuse);
        }

        // GET: Pointeuses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pointeuse pointeuse = db.Pointeuses.Find(id);
            if (pointeuse == null)
            {
                return HttpNotFound();
            }
            return View(pointeuse);
        }

        // POST: Pointeuses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pointeuse pointeuse = db.Pointeuses.Find(id);
            db.Pointeuses.Remove(pointeuse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pointages/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Pointages/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Pointages/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h3>
        @Html.ActionLink("Liste des pointeuses", "Index", "Pointeuses")
    </h3>
</div>

Pointages/Views/Pointeuses/Create.cshtml
@model Pointages.Models.Pointeuse

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pointeuse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Port, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Port, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pointages/Views/Pointeuses/Delete.cshtml
@model Pointages.Models.Pointeuse

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pointeuse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Pointages/Views/Pointeuses/Details.cshtml
@model Pointages.Models.Pointeuse

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pointeuse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Pointages/Views/Pointeuses/Edit.cshtml
@model Pointages.Models.Pointeuse

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pointeuse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Port, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Port, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pointages/Views/Pointeuses/Index.cshtml
@model IEnumerable<Pointages.Models.Pointeuse>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@if (TempData["Success"] != null)
{
    <div class="green">
        <p><strong>Success:</strong> @TempData["Success"].ToString()</p>
    </div>
}
        
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Port)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Port)
        </td>
        <td>
            @Html.ActionLink("Connect", "Connect", new { id = item.ID }) |
            @Html.ActionLink("DisConnect", "DisConnect", new { id = item.ID }) |
            @Html.ActionLink("Read", "Read", new { id = item.ID }) |
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })

        </td>
    </tr>
}

</table>

Pointages/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pointage</title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gestion des Pointages", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
           
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Chronomicro</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>